### ISSUE TITLE
Separate Window Option for Analysis Charts

### ISSUE THREAD

**Issue by petersedivec** [boozallen/argo#1]
The analysis wizard contains several very useful charts (CDF, PDF, etc) that can be viewed relative to the current model and simulation. Currently all of the Argo dialog boxes and interactive chart features are contained within the Excel window. They appear to be separate windows from the look/feel but when attempting to drag a window outside of Excel it starts disappearing. 

It would be nice to have a setting allowing the user to determine the behavior of new Argo windows and if they're separate windows or contained within Excel. Users with large displays or multi monitor setups would likely want to have them displayed outside of Excel.

**Comment by brandonherzog** [comment]
Switched to separate dialogs that can be dragged outside of the main Excel window in v4.
