### ISSUE TITLE
Re-Calculation produces Re-simulation

### ISSUE THREAD

**Issue by blakeatbah** [boozallen/argo#11]
Hitting F9 or recalculating the workbook triggers a re-simulation. Not sure if this is a bug or if this was by design.

**Comment by blakeatbah** [comment]
Gotcha – Thanks Blake.

Sheldon B. Anderson,  Associate
Strategic Innovation Group – NextGen Analytics
Cell: 717-919-3298
www.boozallen.com/argo<http://www.boozallen.com/argo>
www.boozallen.com/polaris<http://www.boozallen.com/polaris>
[cid:image001.png@01D21465.852A9AE0]

**Comment by brandonherzog** [comment]
Fixed in 3.1
