### ISSUE TITLE
Simulation - Open File Prompt

### ISSUE THREAD

**Issue by blakeatbah** [boozallen/argo#12]
After marking a cell as a result using the ribbon button and clicking the simulate button, a new window appears asking to select a file to open. Clicking cancel several times will close the window. 

After deleting the cell, saving the workbook, and opening it back up, a prompt asks to update links to other workbooks. Clicking "Don't Update" closes the window and opens the workbook like normal.

**Comment by brandonherzog** [comment]
Fixed in 3.1
