### ISSUE TITLE
Copying a chart to clipboard

### ISSUE THREAD

**Issue by jlbeerman2** [boozallen/argo#13]
When I am working in the Analysis Wizard and have added the data points I want and go to copy to clipboard, it will only copy the PDF chart, I would like to copy the CDP chart as well.  My current workaround is a screen shot but I was wondering if there was a cleaner way to do this.

**Comment by brandonherzog** [comment]
Thanks for reporting! This was an oversight on our part. We will add the ability to copy the CDF/RCDF images to the next release that should drop within the next two days.

In the meantime, other than screenshots, you can also use the Embed Charts feature to generate standard Excel charts for the PDF and CDF which can then be copied.

**Comment by brandonherzog** [comment]
@jlbeerman2 the ability to copy the CDF/RCDF charts in the Analysis Wizard has been added to today's Argo v4.1.1 release.

As always email getargo@bah.com to receive the download link for the latest version of Argo.
