### ISSUE TITLE
Improved Argo Window labeling for Sensitivity graphs:  "Display in form" option

### ISSUE THREAD

**Issue by petersedivec** [boozallen/argo#2]
On the Sensitivity dialog box there's an option at the bottom with two choices:
- Display in form
- Embed in excel

Suggestion is to relabel these to something that is more user friendly: e.g. 
- Display here or Display to right
- New Excel worksheet

I have written VBA macros and built forms so i'm familiar with forms, however even my first read it was not clear what was meant by the options. It was only after a few times of using it that i realized "form" most likely referred to the VBA form which I think 99% of users will be unfamiliar with the term.

**Comment by blakeboswell** [comment]
Great suggestion.  We definitely put those labels in as placeholders with the intention of coming back and making them more descriptive (but then forgot to re-visit).  I have updated the labels to:

- Display In Dialog
- Embed in Worksheet

These updates are reflected in Argo v3.0.0.
