### ISSUE TITLE
Distribution Random draw

### ISSUE THREAD

**Issue by japsa1974** [boozallen/argo#29]
Hi,

Office 365
Excel Version 1902 Build 11328.20438 Click to Run
Windows 10

I can't seem to draw a fresh random sample from any distribution by pushing F9 to recalculate. 

Argo Setting
Options>Cell Preferences>:Distribution Random Values>Random Draw

Any pointers would be greatly appreciated

Cheers Jason

**Comment by blakeboswell** [comment]
Hey Jason,  

We disabled this feature.  Updating the value of distribution cells on every workbook change was leading to long and unnecessary calculation cycles for large models.

It's key to note that he Cell Preferences setting only impacts what is shown in the workbook.  The simulation is the same regardless of what is shown in the distribution cells. 

We should remove the option from the interface.

Thanks,

Blake

**Comment by japsa1974** [comment]
Thanks Blake for your time, much appreciated.

Jason
