### ISSUE TITLE
Mysterious #VALUE

### ISSUE THREAD

**Issue by blakeboswell** [boozallen/argo#4]
Correctly defined Argo formulas are returning #VALUE after simulation.

[ref1](https://groups.google.com/forum/#!topic/argo-users/iVj7jc-t09o), [ref2](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/argo-users/njtVnBJjeKM)

**Comment by brandonherzog** [comment]
Fixed in 3.1
